version: '3.8'

services:
  db:
    build:
      context: ./mysql
    container_name: mariadb_cont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_NAME: wordpress_db
      MYSQL_USER: userdb
      MYSQL_PASSWORD: passworddb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress
    container_name: wordpress_cont
    restart: always
    environment:
      WORDPRESS_DB_HOST: localhost:3306
      WORDPRESS_DB_USER: userdb
      WORDPRESS_DB_PASSWORD: passworddb
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"

volumes:
  db_data:
  wordpress_data:
