FROM debian:bullseye

ENV WP_DB_NAME 'wordpress_db' \
    WP_DB_USER 'userdb' \
    WP_DB_PASSWORD 'passworddb' \
    WP_DB_HOST 'localhost:3306'

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
        wget \
        ca-certificates \
        apache2 \
        php \
        libapache2-mod-php \
        php-mysql \
        php-mbstring \
        unzip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html
RUN wget -q https://wordpress.org/latest.zip && \
    unzip -q latest.zip && \
    mv wordpress/* . && \
    chown -R www-data:www-data . && \
    chmod -R 755 . && \
    mkdir -p wp-content/uploads && \
    chown -R www-data:www-data wp-content/uploads && \
    rm -rf wordpress latest.zip

RUN echo "ServerName 127.0.0.1" > /etc/apache2/conf-available/servername.conf && \
    a2enconf servername

EXPOSE 80/tcp

VOLUME ["/var/www/html"]

CMD ["apache2ctl", "-D", "FOREGROUND"]