FROM debian:buster

ENV MYSQL_ROOT_PASSWORD='root' \
    MYSQL_NAME='wordpress_db' \
    MYSQL_USER='userdb' \
    MYSQL_PASSWORD='passworddb'

RUN apt-get update && \
    apt-get install -y mariadb-server

RUN mkdir -p /run/mysqld && \
    chown -R mysql:mysql /run/mysqld && \
    sed -i 's/bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/my.cnf && \
    chown -R mysql:mysql /var/lib/mysql /var/run/mysqld && \
    chmod 1777 /var/run/mysqld /var/lib/mysql

RUN rm -rf /run/mysqld/mysqld.sock && \
    mkdir -p /run/mysqld && \
    chown -R mysql:mysql /run/mysqld

RUN service mysql start \
    && mysqladmin -u root password $MYSQL_ROOT_PASSWORD \
    && mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_NAME};" \
    && mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON ${MYSQL_NAME}.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';" \
    && mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"

RUN echo 'bind-address = 0.0.0.0' >> /etc/mysql/my.cnf

EXPOSE 3306/tcp

VOLUME ["/var/lib/mysql"]

CMD ["mysqld"]